Update build3ds

diff --git a/3ds/build3ds b/3ds/build3ds
--- a/3ds/build3ds
+++ b/3ds/build3ds
@@ -31,16 +31,16 @@ dir_filer=~/Documents/3ds/filer
 
 # Directories
 dir_src=~/src
-dir_build=~/src/build
-dir_homebrew=~/src/homebrew
-dir_out=~/src/out
-dir_3ds=~/src/out/3ds
-dir_cia=~/src/out/3ds/sys/cia
-dir_bin=~/src/out/3ds/sys/bin
-dir_firm=~/src/homebrew/firm
-dir_twl=~/src/homebrew/twl
-dir_agb=~/src/homebrew/agb
-dir_tmp=~/src/out/3ds/sys/tmp
+dir_homebrew=$dir_src/homebrew
+dir_firm=$dir_homebrew/firm
+dir_twl=$dir_homebrew/twl
+dir_agb=$dir_homebrew/agb
+dir_build=$dir_src/build
+dir_out=$dir_src/out
+dir_sys=$dir_out/sys
+dir_cia=$dir_sys/cia
+dir_bin=$dir_sys/bin
+dir_tmp=$dir_sys/tmp
 
 # Menu
 echo "";
@@ -49,76 +49,59 @@ echo "[2] Build homebrew";
 echo -n "Select your choice: ";
 read option;
 if [ $option != "1" ] && [ $option != "2" ]; then
-  echo "Invalid choice!";
-  exit 1;
+    echo "Invalid choice!";
+    exit 1;
 fi
 if [ $option = "1" ]; then 
-  # Fetch the homebrew from github
-  mkdir -vp $dir_homebrew
-  rm -rfv $dir_homebrew/*;
-  mkdir -vp $dir_firm/n3ds;
-  mkdir -vp $dir_firm/o3ds;
-  mkdir -vp $dir_twl/n3ds;
-  mkdir -vp $dir_twl/o3ds;
-  mkdir -vp $dir_agb/n3ds;
-  mkdir -vp $dir_agb/o3ds;
-  cd $dir_homebrew;
-  echo "Fetching homebrew...";
-  git clone --recursive https://github.com/d0k3/Decrypt9WIP.git
-  git clone --recursive https://github.com/d0k3/EmuNAND9.git
-  git clone --recursive https://github.com/d0k3/GodMode9.git
-  git clone --recursive https://github.com/AuroraWright/uncart.git
-  git clone --recursive https://github.com/mid-kid/CakesForeveryWan.git
-  git clone --recursive https://github.com/mid-kid/lgy_cakes.git
-  #git clone --recursive https://github.com/mid-kid/3ds_injector.git
-  git clone --recursive https://github.com/Wolfvak/3ds_injector.git
-  git clone --recursive https://github.com/delebile/arm9loaderhax.git
-  git clone --recursive https://github.com/Steveice10/FBI.git
-  git clone --recursive https://github.com/3xkrazy/ftpd.git
-  git clone --recursive -b a9lh https://github.com/Cpasjuste/CtrBootManager.git
-  cd $dir_firm/n3ds;
-  wget $n3ds_firm;
-  wget $n3ds_cetk;
-  cd $dir_firm/o3ds;
-  wget $o3ds_firm;
-  wget $o3ds_cetk;
-  cd $dir_twl/n3ds;
-  wget $n3ds_twl_firm;
-  wget $n3ds_twl_cetk;
-  cd $dir_twl/o3ds;
-  wget $o3ds_twl_firm;
-  wget $o3ds_twl_cetk;
-  cd $dir_agb/n3ds;
-  wget $n3ds_agb_firm;
-  wget $n3ds_agb_cetk;
-  cd $dir_agb/o3ds;
-  wget $o3ds_agb_firm;
-  wget $o3ds_agb_cetk;
-  cd $dir_homebrew;
-  echo "Homebrew up to date! Exiting...";
-  exit 0;
+    # Fetch the homebrew from github
+    mkdir -vp $dir_homebrew
+    rm -rfv $dir_homebrew/*;
+    mkdir -vp $dir_firm/n3ds; mkdir -vp $dir_firm/o3ds;
+    mkdir -vp $dir_twl/n3ds; mkdir -vp $dir_twl/o3ds;
+    mkdir -vp $dir_agb/n3ds; mkdir -vp $dir_agb/o3ds;
+    cd $dir_homebrew;
+    echo "Fetching homebrew...";
+    git clone --recursive https://github.com/d0k3/Decrypt9WIP.git
+    git clone --recursive https://github.com/d0k3/EmuNAND9.git
+    git clone --recursive https://github.com/d0k3/GodMode9.git
+    git clone --recursive https://github.com/AuroraWright/uncart.git
+    git clone --recursive https://github.com/mid-kid/CakesForeveryWan.git
+    git clone --recursive https://github.com/mid-kid/lgy_cakes.git
+    #git clone --recursive https://github.com/mid-kid/3ds_injector.git
+    git clone --recursive https://github.com/Wolfvak/3ds_injector.git
+    git clone --recursive https://github.com/delebile/arm9loaderhax.git
+    git clone --recursive https://github.com/Steveice10/FBI.git
+    git clone --recursive https://github.com/3xkrazy/ftpd.git
+    git clone --recursive -b a9lh https://github.com/Cpasjuste/CtrBootManager.git
+    cd $dir_firm/n3ds; wget $n3ds_firm; wget $n3ds_cetk;
+    cd $dir_firm/o3ds; wget $o3ds_firm; wget $o3ds_cetk;
+    cd $dir_twl/n3ds; wget $n3ds_twl_firm; wget $n3ds_twl_cetk;
+    cd $dir_twl/o3ds; wget $o3ds_twl_firm; wget $o3ds_twl_cetk;
+    cd $dir_agb/n3ds; wget $n3ds_agb_firm; wget $n3ds_agb_cetk;
+    cd $dir_agb/o3ds; wget $o3ds_agb_firm; wget $o3ds_agb_cetk;
+    echo "Homebrew up to date! Exiting...";
+    exit 0;
 fi
 
-# Make directories
-rm -rfv $dir_build;
-rm -rfv $dir_out;
-rm -rfv $dir_src/sdmc*;
-mkdir -vp $dir_build
-mkdir -vp $dir_out
-mkdir -vp $dir_3ds
-mkdir -vp $dir_cia/apps
-mkdir -vp $dir_cia/games
-mkdir -vp $dir_cia/updates
-mkdir -vp $dir_bin
+# Clean src
+rm -rfv $dir_build; rm -rfv $dir_out; rm -rfv $dir_src/sdmc*;
+
+# Make build directories
+mkdir -vp $dir_build;
+mkdir -vp $dir_out;
+mkdir -vp $dir_sys;
+mkdir -vp $dir_cia;
+mkdir -vp $dir_bin;
+mkdir -vp $dir_tmp;
 cp -rRv $dir_homebrew/* $dir_build/;
 
 # Decrypt9WIP
 cd $dir_build/Decrypt9WIP;
-echo "Building Decrypt9WIP...";
-sleep 5s;
+echo "";
+echo "********** Building Decrypt9WIP **********";
 make clean;
 cd $dir_build/Decrypt9WIP/source/decryptor;
-sed -i -e 's|"aeskeydb.bin"|"/3ds/sys/bin/aeskeydb.bin"|g' keys.c;
+sed -i -e 's|"aeskeydb.bin"|"/sys/bin/aeskeydb.bin"|g' keys.c;
 cd $dir_build/Decrypt9WIP;
 make bootstrap;
 mv -v $dir_build/Decrypt9WIP/output/Decrypt9WIP.bin $dir_bin/;
@@ -127,8 +110,8 @@ echo "Done!";
 
 # EmuNAND9
 cd $dir_build/EmuNAND9;
-echo "Building EmuNAND9...";
-sleep 5s;
+echo "";
+echo "********** Building EmuNAND9 **********";
 make clean;
 cd $dir_build/EmuNAND9/source;
 cd $dir_build/EmuNAND9;
@@ -138,8 +121,8 @@ echo "Done!";
 
 # Godmode9
 cd $dir_build/GodMode9;
-echo "Building GodMode9...";
-sleep 5s;
+echo "";
+echo "********** Building GodMode9 **********";
 make clean;
 make bootstrap;
 mv -v $dir_build/GodMode9/output/GodMode9.bin $dir_bin/;
@@ -147,8 +130,8 @@ echo "Done!";
 
 # Uncart
 cd $dir_build/uncart;
-echo "Building Uncart...";
-sleep 5s;
+echo "";
+echo "********** Building Uncart **********";
 make clean;
 make;
 mv -v dir$build/uncart/arm9loaderhax.bin $dir_bin/Uncart.bin;
@@ -156,116 +139,117 @@ echo "Done!";
 
 # CakesFW for n3ds
 cd $dir_build/CakesForeveryWan;
-echo "Building CakesForeveryWan for n3ds...";
-sleep 5s;
+echo "";
+echo "********** Building CakesForeveryWan for n3ds **********";
 make clean;
 cd $dir_build/CakesForeveryWan/source;
-sed -i -e 's|"/cakes"|"/3ds/Cakes-n3ds/cakes"|g' paths.h;
+sed -i -e 's|"/cakes"|"/sys/cakes-n3ds"|g' paths.h;
 sed -i -e 's|PATH_SLOT0X25KEYX|PATH_SLOT0X25KEYX PATH_CAKES|g' paths.h;
 sed -i -e 's|PATH_SLOT0X11KEY96|PATH_SLOT0X11KEY96 PATH_CAKES|g' paths.h;
 cd $dir_build/CakesForeveryWan/CakeBrah/;
-sed -i -e 's|filepath ?=|filepath ?= 3ds/Cakes-n3ds/cakes/|g' Makefile;
+sed -i -e 's|filepath ?=|filepath ?= sys/cakes-n3ds/|g' Makefile;
 cd $dir_build/CakesForeveryWan/CakeHax/;
-sed -i -e 's|filepath ?=|filepath ?= 3ds/Cakes-n3ds/cakes/|g' Makefile;
+sed -i -e 's|filepath ?=|filepath ?= sys/cakes-n3ds/|g' Makefile;
 cd $dir_build/CakesForeveryWan/;
 make;
 mv -v $dir_build/CakesForeveryWan/out/Cakes.dat $dir_build/CakesForeveryWan/out/cakes/;
-cp -v $dir_build/CakesForeveryWan/build/main.bin $dir_build/CakesForeveryWan/out/cakes/cakesfw.bin;
-mv -v $dir_build/CakesForeveryWan/out/cakes $dir_build/CakesForeveryWan/out/3ds/Cakes/;
-cp -v $dir_slotkeybin_files/slot0x25KeyX.bin $dir_build/CakesForeveryWan/out/3ds/Cakes/cakes;
-cp -v $dir_slotkeybin_files/slot0x11Key96.bin $dir_build/CakesForeveryWan/out/3ds/Cakes/cakes;
-cp -rRv $dir_build/CakesForeveryWan/out/3ds/Cakes $dir_3ds/Cakes-n3ds;
-cd $dir_3ds/Cakes-n3ds/cakes;
-cp -v $dir_firm/n3ds/000000* $dir_3ds/Cakes-n3ds/cakes/firmware.bin;
-cp -v $dir_firm/n3ds/cetk $dir_3ds/Cakes-n3ds/cakes/cetk;
-cp -v $dir_cakesfw_files/n3ds/firmkey.bin $dir_3ds/Cakes-n3ds/cakes/firmkey.bin;
-cp -v $dir_twl/n3ds/000000* $dir_3ds/Cakes-n3ds/cakes/twl_firmware.bin;
-cp -v $dir_twl/n3ds/cetk $dir_3ds/Cakes-n3ds/cakes/twl_cetk;
-cp -v $dir_cakesfw_files/n3ds/twl_firmkey.bin $dir_3ds/Cakes-n3ds/cakes/twl_firmkey.bin;
-cp -v $dir_agb/n3ds/000000* $dir_3ds/Cakes-n3ds/cakes/agb_firmware.bin;
-cp -v $dir_agb/n3ds/cetk $dir_3ds/Cakes-n3ds/cakes/agb_cetk;
-cp -v $dir_cakesfw_files/n3ds/agb_firmkey.bin $dir_3ds/Cakes-n3ds/cakes/agb_firmkey.bin;
+mv -v $dir_build/CakesForeveryWan/out/3ds/Cakes/Cakes.3dsx $dir_build/CakesForeveryWan/out/cakes/;
+mv -v $dir_build/CakesForeveryWan/out/3ds/Cakes/Cakes.smdh $dir_build/CakesForeveryWan/out/cakes/;
+cp -v $dir_build/CakesForeveryWan/build/main.bin $dir_build/CakesForeveryWan/out/cakes/cakes.bin;
+cp -v $dir_slotkeybin_files/slot0x25KeyX.bin $dir_build/CakesForeveryWan/out/cakes;
+cp -v $dir_slotkeybin_files/slot0x11Key96.bin $dir_build/CakesForeveryWan/out/cakes;
+mv -v $dir_build/CakesForeveryWan/out/cakes $dir_sys/cakes-n3ds;
+cp -v $dir_firm/n3ds/000000* $dir_sys/cakes-n3ds/firmware.bin;
+cp -v $dir_firm/n3ds/cetk $dir_sys/cakes-n3ds/cetk;
+cp -v $dir_cakesfw_files/n3ds/firmkey.bin $dir_sys/cakes-n3ds/firmkey.bin;
+cp -v $dir_twl/n3ds/000000* $dir_sys/cakes-n3ds/twl_firmware.bin;
+cp -v $dir_twl/n3ds/cetk $dir_sys/cakes-n3ds/twl_cetk;
+cp -v $dir_cakesfw_files/n3ds/twl_firmkey.bin $dir_sys/cakes-n3ds/twl_firmkey.bin;
+cp -v $dir_agb/n3ds/000000* $dir_sys/cakes-n3ds/agb_firmware.bin;
+cp -v $dir_agb/n3ds/cetk $dir_sys/cakes-n3ds/agb_cetk;
+cp -v $dir_cakesfw_files/n3ds/agb_firmkey.bin $dir_sys/cakes-n3ds/agb_firmkey.bin;
 rm -rfv $dir_build/CakesForeveryWan;
 cp -rRv $dir_homebrew/CakesForeveryWan $dir_build/;
 echo "Done!";
 
 # CakesFW for o3ds
 cd $dir_build/CakesForeveryWan;
-echo "Building CakesForeveryWan for o3ds...";
-sleep 5s;
+echo "";
+echo "********** Building CakesForeveryWan for o3ds **********";
 make clean;
 cd $dir_build/CakesForeveryWan/source;
-sed -i -e 's|"/cakes"|"/3ds/Cakes-o3ds/cakes"|g' paths.h;
+sed -i -e 's|"/cakes"|"/sys/cakes-o3ds"|g' paths.h;
 sed -i -e 's|PATH_SLOT0X25KEYX|PATH_SLOT0X25KEYX PATH_CAKES|g' paths.h;
 sed -i -e 's|PATH_SLOT0X11KEY96|PATH_SLOT0X11KEY96 PATH_CAKES|g' paths.h;
 cd $dir_build/CakesForeveryWan/CakeBrah/;
-sed -i -e 's|filepath ?=|filepath ?= 3ds/Cakes-o3ds/cakes/|g' Makefile;
+sed -i -e 's|filepath ?=|filepath ?= sys/cakes-o3ds/|g' Makefile;
 cd $dir_build/CakesForeveryWan/CakeHax/;
-sed -i -e 's|filepath ?=|filepath ?= 3ds/Cakes-o3ds/cakes/|g' Makefile;
+sed -i -e 's|filepath ?=|filepath ?= sys/cakes-o3ds/|g' Makefile;
 cd $dir_build/CakesForeveryWan/;
 make;
 mv -v $dir_build/CakesForeveryWan/out/Cakes.dat $dir_build/CakesForeveryWan/out/cakes/;
-cp -v $dir_build/CakesForeveryWan/build/main.bin $dir_build/CakesForeveryWan/out/cakes/cakesfw.bin;
-mv -v $dir_build/CakesForeveryWan/out/cakes $dir_build/CakesForeveryWan/out/3ds/Cakes/;
-cp -v $dir_slotkeybin_files/slot0x25KeyX.bin $dir_build/CakesForeveryWan/out/3ds/Cakes/cakes;
-cp -v $dir_slotkeybin_files/slot0x11Key96.bin $dir_build/CakesForeveryWan/out/3ds/Cakes/cakes;
-cp -rRv $dir_build/CakesForeveryWan/out/3ds/Cakes $dir_3ds/Cakes-o3ds;
-cd $dir_3ds/Cakes-o3ds/cakes;
-cp -v $dir_firm/o3ds/000000* $dir_3ds/Cakes-o3ds/cakes/firmware.bin;
-cp -v $dir_firm/o3ds/cetk $dir_3ds/Cakes-o3ds/cakes/cetk;
-cp -v $dir_cakesfw_files/o3ds/firmkey.bin $dir_3ds/Cakes-o3ds/cakes/firmkey.bin;
-cp -v $dir_twl/o3ds/000000* $dir_3ds/Cakes-o3ds/cakes/twl_firmware.bin;
-cp -v $dir_twl/o3ds/cetk $dir_3ds/Cakes-o3ds/cakes/twl_cetk;
-cp -v $dir_cakesfw_files/o3ds/twl_firmkey.bin $dir_3ds/Cakes-o3ds/cakes/twl_firmkey.bin;
-cp -v $dir_agb/o3ds/000000* $dir_3ds/Cakes-o3ds/cakes/agb_firmware.bin;
-cp -v $dir_agb/o3ds/cetk $dir_3ds/Cakes-o3ds/cakes/agb_cetk;
-cp -v $dir_cakesfw_files/o3ds/agb_firmkey.bin $dir_3ds/Cakes-o3ds/cakes/agb_firmkey.bin;
+mv -v $dir_build/CakesForeveryWan/out/3ds/Cakes/Cakes.3dsx $dir_build/CakesForeveryWan/out/cakes/;
+mv -v $dir_build/CakesForeveryWan/out/3ds/Cakes/Cakes.smdh $dir_build/CakesForeveryWan/out/cakes/;
+cp -v $dir_build/CakesForeveryWan/build/main.bin $dir_build/CakesForeveryWan/out/cakes/cakes.bin;
+cp -v $dir_slotkeybin_files/slot0x25KeyX.bin $dir_build/CakesForeveryWan/out/cakes;
+cp -v $dir_slotkeybin_files/slot0x11Key96.bin $dir_build/CakesForeveryWan/out/cakes;
+mv -v $dir_build/CakesForeveryWan/out/cakes $dir_sys/cakes-o3ds;
+cp -v $dir_firm/o3ds/000000* $dir_sys/cakes-o3ds/firmware.bin;
+cp -v $dir_firm/o3ds/cetk $dir_sys/cakes-o3ds/cetk;
+cp -v $dir_cakesfw_files/o3ds/firmkey.bin $dir_sys/cakes-o3ds/firmkey.bin;
+cp -v $dir_twl/o3ds/000000* $dir_sys/cakes-o3ds/twl_firmware.bin;
+cp -v $dir_twl/o3ds/cetk $dir_sys/cakes-o3ds/twl_cetk;
+cp -v $dir_cakesfw_files/o3ds/twl_firmkey.bin $dir_sys/cakes-o3ds/twl_firmkey.bin;
+cp -v $dir_agb/o3ds/000000* $dir_sys/cakes-o3ds/agb_firmware.bin;
+cp -v $dir_agb/o3ds/cetk $dir_sys/cakes-o3ds/agb_cetk;
+cp -v $dir_cakesfw_files/o3ds/agb_firmkey.bin $dir_sys/cakes-o3ds/agb_firmkey.bin;
 echo "Done!";
 
 # lgy_cakes
-echo "Building lgy_cakes..."
 cd $dir_build/lgy_cakes;
-sleep 5s;
+echo "";
+echo "********** Building lgy_cakes **********"
+make clean;
 make;
-cp -v *.cake $dir_3ds/Cakes-n3ds/cakes/patches/;
-cp -v *.cake $dir_3ds/Cakes-o3ds/cakes/patches/;
+cp -v *.cake $dir_sys/cakes-n3ds/patches/;
+cp -v *.cake $dir_sys/cakes-o3ds/patches/;
 echo "Done!";
 
 << COMMENT1
 # 3ds_injector
-echo "Building 3ds_injector..."
 cd $dir_build/3ds_injector;
-sleep 5s;
+echo "";
+echo "********** Building 3ds_injector **********"
 make clean;
 make;
-cp -v *.cake $dir_3ds/Cakes-n3ds/cakes/patches/;
-cp -v *.cake $dir_3ds/Cakes-o3ds/cakes/patches/;
+cp -v *.cake $dir_sys/cakes-n3ds/patches/;
+cp -v *.cake $dir_sys/cakes-o3ds/patches/;
 echo "Done!";
 COMMENT1
 
 # 3ds_injector
-echo "Building 3ds_injector..."
 cd $dir_build/3ds_injector;
-sleep 5s;
+echo "";
+echo "********** Building 3ds_injector **********"
 make clean;
 cd $dir_build/3ds_injector/source/;
-sed -i -e 's|"/injector/"|"/3ds/sys/3ds_injector/"|g' paths.h;
+sed -i -e 's|"/injector/"|"/sys/3ds_injector/"|g' paths.h;
 cd $dir_build/3ds_injector;
 make;
-cp -v *.cake $dir_3ds/Cakes-n3ds/cakes/patches/;
-cp -v *.cake $dir_3ds/Cakes-o3ds/cakes/patches/;
-cp -rRv $dir_3ds_injector $dir_3ds/sys;
+cp -v *.cake $dir_sys/cakes-n3ds/patches/;
+cp -v *.cake $dir_sys/cakes-o3ds/patches/;
+mv -v $dir_3ds_injector $dir_sys/;
 echo "Done!";
 
 # Arm9loaderhax n3ds
-echo "Building Arm9loaderhax for n3DS...";
-sleep 5s;
 cd $dir_build/arm9loaderhax;
+echo "";
+echo "********** Building Arm9LoaderHax for n3DS **********";
 make clean;
 cd $dir_build/arm9loaderhax/payload_stage2/source;
-sed -i -e 's|"arm9loaderhax.bin"|"/3ds/sys/bin/boot.bin"|g' main.c;
+sed -i -e 's|"arm9loaderhax.bin"|"/sys/bin/boot.bin"|g' main.c;
 cd $dir_build/arm9loaderhax/payload_installer/installer/source;
-sed -i -e 's|"sdmc:/arm9loaderhax.pack"|"sdmc:/3ds/arm9loaderhax-n3ds/arm9loaderhax.pack"|g' main.c
+sed -i -e 's|"sdmc:/arm9loaderhax.pack"|"sdmc:/sys/arm9loaderhax-n3ds/arm9loaderhax.pack"|g' main.c
 cd $dir_build/arm9loaderhax/data_input;
 cp -v $dir_a9lh_files/new3ds10.firm $dir_build/arm9loaderhax/data_input;
 cp -v $dir_a9lh_files/new3ds90.firm $dir_build/arm9loaderhax/data_input;
@@ -273,20 +257,20 @@ cp -v $dir_a9lh_files/secret_sector.bin $dir_build/arm9loaderhax/data_input;
 cp -v $dir_a9lh_files/otp.bin-n3ds $dir_build/arm9loaderhax/data_input/otp.bin;
 cd $dir_build/arm9loaderhax/;
 make;
-mv -v $dir_build/arm9loaderhax/data_output $dir_3ds/arm9loaderhax-n3ds;
+mv -v $dir_build/arm9loaderhax/data_output $dir_sys/arm9loaderhax-n3ds;
 rm -rfv $dir_build/arm9loaderhax;
 cp -rRv $dir_homebrew/arm9loaderhax $dir_build/;
 echo "Done!";
 
 # Arm9loaderhax o3ds
-echo "Building Arm9loaderhax for o3DS...";
-sleep 5s;
 cd $dir_build/arm9loaderhax;
+echo "";
+echo "********** Building Arm9loaderhax for o3DS **********";
 make clean;
 cd $dir_build/arm9loaderhax/payload_stage2/source;
-sed -i -e 's|"arm9loaderhax.bin"|"/3ds/sys/bin/boot.bin"|g' main.c;
+sed -i -e 's|"arm9loaderhax.bin"|"/sys/bin/boot.bin"|g' main.c;
 cd $dir_build/arm9loaderhax/payload_installer/installer/source;
-sed -i -e 's|"sdmc:/arm9loaderhax.pack"|"sdmc:/3ds/arm9loaderhax-o3ds/arm9loaderhax.pack"|g' main.c
+sed -i -e 's|"sdmc:/arm9loaderhax.pack"|"sdmc:/sys/arm9loaderhax-o3ds/arm9loaderhax.pack"|g' main.c
 cd $dir_build/arm9loaderhax/data_input;
 cp -v $dir_a9lh_files/new3ds10.firm $dir_build/arm9loaderhax/data_input;
 cp -v $dir_a9lh_files/new3ds90.firm $dir_build/arm9loaderhax/data_input;
@@ -294,32 +278,31 @@ cp -v $dir_a9lh_files/secret_sector.bin $dir_build/arm9loaderhax/data_input;
 cp -v $dir_a9lh_files/otp.bin-o3ds $dir_build/arm9loaderhax/data_input/otp.bin;
 cd $dir_build/arm9loaderhax/;
 make;
-mv -v $dir_build/arm9loaderhax/data_output $dir_3ds/arm9loaderhax-o3ds;
+mv -v $dir_build/arm9loaderhax/data_output $dir_sys/arm9loaderhax-o3ds;
 echo "Done!";
 
 # FBI
-echo "Building FBI...";
-sleep 5s;
 cd $dir_build/FBI;
+echo "";
+echo "********** Building FBI **********";
 make clean;
 make;
 cp -v $dir_build/FBI/output/FBI.cia $dir_cia/apps/;
 echo "Done!";
 
 # ftpd
-echo "Building ftpd...";
-sleep 5s;
 cd $dir_build/ftpd;
+echo "********** Building ftpd **********";
 make clean;
 make;
 cp -v $dir_build/ftpd/output/ftpd.cia $dir_cia/apps/;
 echo "Done!";
 
 # CtrBootManager
-echo "Building CtrBootManager";
-sleep 5s;
+echo "";
+echo "********** Building CtrBootManager **********";
 cd $dir_build/CtrBootManager/source;
-sed -i -e 's|#define CONFIG_PATH "/a9lh.cfg"|#define CONFIG_PATH "/3ds/sys/bin/a9lh.cfg"|g' config.h;
+sed -i -e 's|#define CONFIG_PATH "/a9lh.cfg"|#define CONFIG_PATH "/sys/bin/boot.cfg"|g' config.h;
 cd $dir_build/CtrBootManager;
 mkdir build;
 cd build;
@@ -342,56 +325,54 @@ highlight = 000000
 borders = ffffff
 font1 = ffffff
 font2 = ff0000
-bgImgTop = /3ds/sys/bin/bgTop.bin
-bgImgBot = /3ds/sys/bin/bgBot.bin
+bgImgTop = /sys/bin/bgTop.bin
+bgImgBot = /sys/bin/bgBot.bin
 
 [entry]
 title = CakesFW
-path =  /3ds/Cakes-n3ds/cakes/cakesfw.bin
+path = /sys/cakes-n3ds/cakes.bin
 offset = 0
 key = -1
 
 [entry]
 title = Decrypt9
-path =  /3ds/sys/bin/Decrypt9WIP.bin
+path = /sys/bin/Decrypt9WIP.bin
 offset = 0
 key = 3
 
 [entry]
 title = EmuNAND9
-path =  /3ds/sys/bin/EmuNAND9.bin
+path = /sys/bin/EmuNAND9.bin
 offset = 0
 key = 3
 
 [entry]
 title = GodMode9
-path =  /3ds/sys/bin/GodMode9.bin
+path = /sys/bin/GodMode9.bin
 offset = 0
 key = 3
 
 [entry]
 title = Uncart
-path =  /3ds/sys/bin/Uncart.bin
+path = /sys/bin/Uncart.bin
 offset = 0
 key = 3
 
 [entry]
 title = Arm9LoaderHax
-path =  /3ds/arm9loaderhax-n3ds/arm9loaderhax.bin
+path = /sys/arm9loaderhax-n3ds/arm9loaderhax.bin
 offset = 0
-key = 3" > $dir_bin/a9lh.cfg;
+key = 3" > $dir_bin/boot.cfg;
 echo "Done!";
 
 # Copy files over
 cp -v $dir_cia_files/apps/*.cia $dir_cia/apps/;
 cp -v $dir_misc_files/boot.3dsx $dir_out;
 cp -rRv $dir_filer $dir_out/;
-mkdir -vp $dir_3ds/sys/tmp/db;
-cd $dir_3ds/sys/tmp/db;
-touch title.db;
-touch import.db;
-cp -rRv $dir_decrypt9wip_files/n3ds/ $dir_tmp;
-cp -rRv $dir_decrypt9wip_files/o3ds/ $dir_tmp;
+mkdir -vp $dir_tmp/db;
+touch $dir_tmp/title.db $dir_tmp/import.db;
+cp -rRv $dir_decrypt9wip_files/n3ds $dir_tmp/hs-n3ds;
+cp -rRv $dir_decrypt9wip_files/o3ds $dir_tmp/hs-o3ds;
 
 # Clean up
 cd ~/src;
