Update build3ds

diff --git a/3ds/build3ds b/3ds/build3ds
--- a/3ds/build3ds
+++ b/3ds/build3ds
@@ -27,6 +27,7 @@ o3ds_agb_cetk=http://nus.cdn.c.shop.nintendowifi.net/ccs/download/00040138000002
 ntr=https://github.com/44670/BootNTR/releases/download/3.2/NTR.3.2.zip
 
 # Directories
+dir_src=~/src
 dir_build=~/src/build
 dir_out=~/src/out
 dir_3ds=~/src/out/3ds
@@ -52,18 +53,43 @@ mkdir -vp $dir_cia/games
 mkdir -vp $dir_cia/updates
 mkdir -vp $dir_bin
 
-# Fetch the homebrew from github
-cd $dir_build;
-echo "Fetching homebrew...";
-git clone --recursive https://github.com/d0k3/Decrypt9WIP.git
-git clone --recursive https://github.com/d0k3/EmuNAND9.git
-git clone --recursive https://github.com/d0k3/GodMode9.git
-git clone --recursive https://github.com/mid-kid/CakesForeveryWan.git
-git clone --recursive https://github.com/Reisyukaku/ReiNand.git
-git clone --recursive https://github.com/delebile/arm9loaderhax.git
-git clone --recursive https://github.com/yellows8/hblauncher_loader.git
-git clone --recursive https://github.com/44670/BootNTR.git
-git clone --recursive -b a9lh https://github.com/Cpasjuste/CtrBootManager.git
+# Menu
+echo [1] Downloand and build from source;
+echo [2] Build from local source;
+echo -n "Select your choice: "
+read option
+
+if [option !=1 || option !=2]; then
+  echo "Invalid choice!";
+  exit 1;
+fi
+
+if [option = 1 ]; then 
+  # Fetch the homebrew from github
+  cd $dir_build;
+  echo "Fetching homebrew...";
+  git clone --recursive https://github.com/d0k3/Decrypt9WIP.git
+  git clone --recursive https://github.com/d0k3/EmuNAND9.git
+  git clone --recursive https://github.com/d0k3/GodMode9.git
+  git clone --recursive https://github.com/mid-kid/CakesForeveryWan.git
+  git clone --recursive https://github.com/Reisyukaku/ReiNand.git
+  git clone --recursive https://github.com/delebile/arm9loaderhax.git
+  git clone --recursive https://github.com/yellows8/hblauncher_loader.git
+  git clone --recursive https://github.com/44670/BootNTR.git
+  git clone --recursive -b a9lh https://github.com/Cpasjuste/CtrBootManager.git
+fi
+
+if [option = 2]; then
+  rm -rf $dir_src/sdmc*
+  cd $dir_build/Decrypt9WIP && make clean;
+  cd $dir_build/EmuNAND9 && make clean;
+  cd $dir_build/GodMode9 && make clean;
+  cd $dir_build/CakesForeveryWan && make clean;
+  cd $dir_build/ReiNand && make clean;
+  cd $dir_build/arm9loaderhax && make clean;
+  cd $dir_build/hblauncher_loader && make clean;
+  cd $dir_build/BootNTR && make clean && rm -rf ntr_build;
+fi
 
 # Decrypt9WIP
 cd $dir_build/Decrypt9WIP;
@@ -71,8 +97,10 @@ echo "Building Decrypt9WIP...";
 sleep 5s;
 make clean;
 cd $dir_build/Decrypt9WIP/source/decryptor;
-sed -i -e 's|"aeskeydb.bin"|"/3ds/sys/bin/aeskeydb.bin"|g' keys.c;
-sed -i -e 's|"slot0x%02X%s.bin"|"/3ds/sys/bin/slot0x%02X%s.bin"|g' keys.c;
+if [option = 1]; then
+  sed -i -e 's|"aeskeydb.bin"|"/3ds/sys/bin/aeskeydb.bin"|g' keys.c;
+  sed -i -e 's|"slot0x%02X%s.bin"|"/3ds/sys/bin/slot0x%02X%s.bin"|g' keys.c;
+fi
 cd $dir_build/Decrypt9WIP;
 make;
 mv -v $dir_build/Decrypt9WIP/output/Decrypt9WIP.bin $dir_bin/;
@@ -93,8 +121,10 @@ echo "Building GodMode9...";
 sleep 5s;
 make clean;
 cd $dir_build/GodMode9/source/nand;
-sed -i -e 's|"%s/aeskeydb.bin", folder|"/3ds/sys/bin/slot0x05KeyY.bin"|g' nand.c;
-sed -i -e 's|"%s/slot0x%02XKey%.10s", folder|"/3ds/sys/bin/slot0x%02XKey%.10s"|g' nand.c;
+if [option = 1]; then
+  sed -i -e 's|"%s/aeskeydb.bin", folder|"/3ds/sys/bin/slot0x05KeyY.bin"|g' nand.c;
+  sed -i -e 's|"%s/slot0x%02XKey%.10s", folder|"/3ds/sys/bin/slot0x%02XKey%.10s"|g' nand.c;
+fi
 cd $dir_build/GodMode9;
 make bootstrap;
 mv -v $dir_build/GodMode9/output/GodMode9.bin $dir_bin/;
@@ -105,15 +135,17 @@ cd $dir_build/CakesForeveryWan;
 echo "Building CakesForeveryWan...";
 sleep 5s;
 make clean;
-cd $dir_build/CakesForeveryWan/source;
-sed -i -e 's|"/cakes"|"/3ds/Cakes/cakes"|g' paths.h;
-sed -i -e '7i#define PATH_BIN "/3ds/sys/bin"\' paths.h;
-sed -i -e 's|#define PATH_SLOT0X25KEYX "/slot0x25keyX.bin"|#define PATH_SLOT0X25KEYX PATH_BIN "/slot0x25keyX.bin"|g' paths.h;
-sed -i -e 's|#define PATH_SLOT0X11KEY96 "/slot0x11key96.bin"|#define PATH_SLOT0X11KEY96 PATH_BIN "/slot0x11key96.bin"|g' paths.h;
-cd $dir_build/CakesForeveryWan/CakeBrah/;
-sed -i -e 's|filepath ?=|filepath ?= 3ds/Cakes/cakes/|g' Makefile;
-cd $dir_build/CakesForeveryWan/CakeHax/;
-sed -i -e 's|filepath ?=|filepath ?= 3ds/Cakes/cakes/|g' Makefile;
+if [option = 1]; then
+  cd $dir_build/CakesForeveryWan/source;
+  sed -i -e 's|"/cakes"|"/3ds/Cakes/cakes"|g' paths.h;
+  sed -i -e '7i#define PATH_BIN "/3ds/sys/bin"\' paths.h;
+  sed -i -e 's|#define PATH_SLOT0X25KEYX "/slot0x25keyX.bin"|#define PATH_SLOT0X25KEYX PATH_BIN "/slot0x25keyX.bin"|g' paths.h;
+  sed -i -e 's|#define PATH_SLOT0X11KEY96 "/slot0x11key96.bin"|#define PATH_SLOT0X11KEY96 PATH_BIN "/slot0x11key96.bin"|g' paths.h;
+  cd $dir_build/CakesForeveryWan/CakeBrah/;
+  sed -i -e 's|filepath ?=|filepath ?= 3ds/Cakes/cakes/|g' Makefile;
+  cd $dir_build/CakesForeveryWan/CakeHax/;
+  sed -i -e 's|filepath ?=|filepath ?= 3ds/Cakes/cakes/|g' Makefile;
+fi
 cd $dir_build/CakesForeveryWan/;
 make;
 mv -v $dir_build/CakesForeveryWan/out/Cakes.dat $dir_build/CakesForeveryWan/out/cakes/;
@@ -153,16 +185,18 @@ echo "Building ReiNand...";
 cd $dir_build/ReiNand;
 sleep 5s;
 make clean;
-cd $dir_build/ReiNand/CakeBrah;
-sed -i -e 's|filepath ?=|filepath ?= 3ds/ReiNand/rei/|g' Makefile;
-cd $dir_build/ReiNand/CakeHax;
-sed -i -e 's|filepath ?=|filepath ?= 3ds/ReiNand/rei/|g' Makefile;
-cd $dir_build/ReiNand/source;
-sed -i -e 's|"/rei/splash.bin"|"/3ds/ReiNand/rei/splash.bin"|g' draw.c;
-sed -i -e 's|"/rei/firmware.bin"|"/3ds/ReiNand/rei/firmware.bin"|g' firm.c;
-sed -i -e 's|"/rei/emunand/emunand.bin"|"/3ds/ReiNand/rei/emunand/emunand.bin"|g' firm.c;
-sed -i -e 's|"/rei/thread/arm9.bin"|"/3ds/ReiNand/rei/thread/arm9.bin"|g' firm.c;
-sed -i -e 's|"/rei/loader.cxi"|"/3ds/ReiNand/rei/loader.cxi"|g' firm.c;
+if [option = 1]; then
+  cd $dir_build/ReiNand/CakeBrah;
+  sed -i -e 's|filepath ?=|filepath ?= 3ds/ReiNand/rei/|g' Makefile;
+  cd $dir_build/ReiNand/CakeHax;
+  sed -i -e 's|filepath ?=|filepath ?= 3ds/ReiNand/rei/|g' Makefile;
+  cd $dir_build/ReiNand/source;
+  sed -i -e 's|"/rei/splash.bin"|"/3ds/ReiNand/rei/splash.bin"|g' draw.c;
+  sed -i -e 's|"/rei/firmware.bin"|"/3ds/ReiNand/rei/firmware.bin"|g' firm.c;
+  sed -i -e 's|"/rei/emunand/emunand.bin"|"/3ds/ReiNand/rei/emunand/emunand.bin"|g' firm.c;
+  sed -i -e 's|"/rei/thread/arm9.bin"|"/3ds/ReiNand/rei/thread/arm9.bin"|g' firm.c;
+  sed -i -e 's|"/rei/loader.cxi"|"/3ds/ReiNand/rei/loader.cxi"|g' firm.c;
+fi
 cd $dir_build/ReiNand;
 make;
 mv -v $dir_build/ReiNand/out/rei $dir_build/ReiNand/out/3ds/ReiNand/;
@@ -176,8 +210,10 @@ echo "Building Arm9loaderhax for n3DS...";
 sleep 5s;
 cd $dir_build/arm9loaderhax;
 make clean;
-cd $dir_build/arm9loaderhax/payload_stage2/source;
-sed -i -e 's|"arm9loaderhax.bin"|"/3ds/sys/bin/arm9loaderhax.bin"|g' main.c;
+if [option = 1]; then
+  cd $dir_build/arm9loaderhax/payload_stage2/source;
+  sed -i -e 's|"arm9loaderhax.bin"|"/3ds/sys/bin/arm9loaderhax.bin"|g' main.c;
+fi
 cd $dir_build/arm9loaderhax/data_input;
 cp -v $dir_a9lh_files/new3ds10.firm $dir_build/arm9loaderhax/data_input;
 cp -v $dir_a9lh_files/new3ds90.firm $dir_build/arm9loaderhax/data_input;
@@ -209,8 +245,10 @@ echo "Building hblaunhcer_loader...";
 sleep 5s;
 cd $dir_build/hblauncher_loader;
 make clean;
-cd $dir_build/hblauncher_loader/source;
-sed -i -e 's|"sdmc:/hblauncherloader_otherapp_payload_%s.bin"|"sdmc:/3ds/sys/bin/hblauncherloader_otherapp_payload_%s.bin"|g' hblauncher_loader.c;
+if if [option = 1]; then
+  cd $dir_build/hblauncher_loader/source;
+  sed -i -e 's|"sdmc:/hblauncherloader_otherapp_payload_%s.bin"|"sdmc:/3ds/sys/bin/hblauncherloader_otherapp_payload_%s.bin"|g' hblauncher_loader.c;
+fi
 cd $dir_build/hblauncher_loader;
 make;
 cp -v hblauncher_loader.cia $dir_cia/apps/;
@@ -219,9 +257,14 @@ echo "Done!";
 # CtrBootManager
 echo "Building CtrBootManager";
 sleep 5s;
-cd $dir_build/CtrBootManager/source;
-sed -i -e 's|#define CONFIG_PATH "/a9lh.cfg"|#define CONFIG_PATH "/3ds/sys/bin/a9lh.cfg"|g' config.h;
+if [option = 1]; then
+  cd $dir_build/CtrBootManager/source;
+  sed -i -e 's|#define CONFIG_PATH "/a9lh.cfg"|#define CONFIG_PATH "/3ds/sys/bin/a9lh.cfg"|g' config.h;
+fi
 cd $dir_build/CtrBootManager;
+if [option = 2]; then
+  rm -rf build;
+fi
 mkdir build;
 cd build;
 cmake -DCMAKE_TOOLCHAIN_FILE=../DevkitArm3DS.cmake ../
@@ -291,9 +334,14 @@ cp -v $dir_misc/makerom $dir_build/BootNTR/lib/ctrcommon/tools/makerom-linux;
 chmod u+x $dir_build/BootNTR/lib/ctrcommon/tools/*linux;
 make;
 cp -v $dir_build/BootNTR/output/BootNTR.cia $dir_cia/apps/;
+if [option = 2]; then
+  rm -rf ntr_zip;
+fi
+mkdir ntr_zip;
+cd ntr_zip;
 wget $ntr;
 unzip *.zip;
-cp -v $dir_build/BootNTR/ntr.bin $dir_out/;
+cp -v $dir_build/BootNTR/ntr_build/ntr.bin $dir_out/;
 echo "Done!";
 
 # Copy files over
